package no.nav.dagpenger.iverksett.konsumenter.økonomi.utbetalingsoppdrag.domene

import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.JsonProcessingException
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonSerializer
import com.fasterxml.jackson.databind.KeyDeserializer
import com.fasterxml.jackson.databind.SerializerProvider
import no.nav.dagpenger.kontrakter.felles.StønadType
import no.nav.dagpenger.kontrakter.felles.objectMapper
import no.nav.dagpenger.kontrakter.iverksett.Ferietillegg
import java.io.IOException

data class StønadTypeOgFerietillegg(
    val stønadstype: StønadType,
    val ferietillegg: Ferietillegg? = null,
)

class StønadTypeOgFerietilleggKeySerializer : JsonSerializer<StønadTypeOgFerietillegg>() {
    @Throws(IOException::class, JsonProcessingException::class)
    override fun serialize(value: StønadTypeOgFerietillegg?, gen: JsonGenerator?, serializers: SerializerProvider?) {
        gen?.let { jGen ->
            value?.let { stønadtypeOgFerietillegg ->
                jGen.writeFieldName(objectMapper.writeValueAsString(stønadtypeOgFerietillegg))
            } ?: jGen.writeNull()
        }
    }
}

class StønadTypeOgFerietilleggKeyDeserializer : KeyDeserializer() {
    @Throws(IOException::class, JsonProcessingException::class)
    override fun deserializeKey(key: String?, ctxt: DeserializationContext?): StønadTypeOgFerietillegg? {
        return key?.let { objectMapper.readValue(key, StønadTypeOgFerietillegg::class.java) }
    }
}

fun StønadTypeOgFerietillegg.tilKlassifisering() = when (this.stønadstype) {
    StønadType.DAGPENGER_ARBEIDSSOKER_ORDINAER -> when (ferietillegg) {
        Ferietillegg.ORDINAER -> "DPORASFE"
        Ferietillegg.AVDOD -> "DPORASFE-IOP"
        null -> "DPORAS"
    }
    StønadType.DAGPENGER_PERMITTERING_ORDINAER -> when (ferietillegg) {
        Ferietillegg.ORDINAER -> "DPPEASFE1"
        Ferietillegg.AVDOD -> "DPPEASFE1-IOP"
        null -> "DPPEAS"
    }
    StønadType.DAGPENGER_PERMITTERING_FISKEINDUSTRI -> when (ferietillegg) {
        Ferietillegg.ORDINAER -> "DPPEFIFE1"
        Ferietillegg.AVDOD -> "DPPEFIFE1-IOP"
        null -> "DPPEFI"
    }
    StønadType.DAGPENGER_EOS -> when (ferietillegg) {
        Ferietillegg.ORDINAER -> "DPFEASISP"
        Ferietillegg.AVDOD -> throw IllegalArgumentException("Eksport-gruppen har ingen egen kode for ferietillegg til avdød")
        null -> "DPDPASISP1"
    }
    StønadType.TILTAKSPENGER -> "TPTPTILTAK"
    StønadType.TILTAKSPENGER_BARNETILLEGG_HOYERE_UTDANNING -> "TPBTHOYUTD"
    StønadType.TILTAKSPENGER_BARNETILLEGG_JOBBKLUBB_2009 -> "TPBTJK2009"
    StønadType.TILTAKSPENGER_UTDANNING -> "TPTPUTD"
    StønadType.TILTAKSPENGER_AVKLARING_ANDRE_GRUPPER -> "TPTPAAG"
    StønadType.TILTAKSPENGER_SEMESTERAVGIFT_OPPFOLGING_ANDRE_GRUPPER -> "TPSAOPPFAG"
    StønadType.TILTAKSPENGER_BARNETILLEGG_ENKELTPLASS_AMO -> "TPBTEPAMO"
    StønadType.TILTAKSPENGER_HOYERE_UTDANNING -> "TPTPHOYUTD"
    StønadType.TILTAKSPENGER_JOBBKLUBB_FRA_2009 -> "TPTPJK2009"
    StønadType.TILTAKSPENGER_ARBEIDSMARKEDSTILTAK -> "TPTPTILTAK"
    StønadType.TILTAKSPENGER_BARNETILLEGG_GRUNNSKOLE_VGS_OG_HOYERE_YRKESFAG -> "TPBTGRVGSHOY"
    StønadType.TILTAKSPENGER_BARNETILLEGG_IPS -> "TPBTIPS"
    StønadType.TILTAKSPENGER_BARNETILLEGG_ARBEIDSTRENINGSTILTAK -> "TPBTATTILT"
    StønadType.TILTAKSPENGER_ENKELTPLASS_VGS_ELLER_HOYERE_UTDANNING -> "TPTPEPVGSHOU"
    StønadType.TILTAKSPENGER_EKSAMENSGEBYR_GRUNNSKOLE_VGS_OG_HOYERE_UTDANNING -> "TPEGGRVGSHOY"
    StønadType.TILTAKSPENGER_GRUPPE_VGS_ELLER_HOYERE_UTDANNING -> "TPTPGRVGSHOY"
    StønadType.TILTAKSPENGER_SKOLEPENGER_GRUPPE_AMO -> "TPSPGRAMO"
    StønadType.TILTAKSPENGER_BARNETILLEGG_GRUPPE_AMO -> "TPBTGRAMO"
    StønadType.TILTAKSPENGER_INKLUDERINGSTILSKUDD -> "TPTPINKLTILSK"
    StønadType.TILTAKSPENGER_SEMESTERAVGIFT_ENKELT_VGS_OG_HOYERE_UTDANNING -> "TPSAEPVGSHOY"
    StønadType.TILTAKSPENGER_SKOLEPENGER_HOYERE_UTDANNING -> "TPSPHOYUTD"
    StønadType.TILTAKSPENGER_BARNETILLEGG_UTDANNING -> "TPBTUTD"
    StønadType.TILTAKSPENGER_SKOLEPENGER_ARBEIDSTRNINGSTILTAK -> "TPSPATTILT"
    StønadType.TILTAKSPENGER_BARNETILLEGG_OPPFOLGING_ANDRE_GRUPPER -> "TPBTOPPFAGR"
    StønadType.TILTAKSPENGER_EKSAMENSGEBYR_AMO -> "TPEGAMO"
    StønadType.TILTAKSPENGER_FORSOK_LENGRE_VARIGHET -> "TPTPFLV"
    StønadType.TILTAKSPENGER_UTVIDET_AVKLARING_OG_OPPFOLGING -> "TPTPUAOPPF"
    StønadType.TILTAKSPENGER_BARNETILLEGG_ARB_R_REHAB_ANDRE_GR_DAG -> "TPBTARREHABAGDAG"
    StønadType.TILTAKSPENGER_MENTOR -> "TPTPM"
    StønadType.TILTAKSPENGER_TILSYNSTILLEGG_AMO -> "TPTTAMO"
    StønadType.TILTAKSPENGER_SKOLEPENGER_GRUPPE_VGS_OG_HOYERE -> "TPSPGRVGSHOY"
    StønadType.TILTAKSPENGER_SKOLEPENGER_ENKELTPLASS_VGS_OG_HOYERE -> "TPSPEPVGSHOY"
    StønadType.TILTAKSPENGER_BARNETILLEGG_AVKLARING_ANDRE_GRUPPER -> "TPBTAAGR"
    StønadType.TILTAKSPENGER_INDIVIDUELL_JOBBSTOTTE -> "TPTPIPS"
    StønadType.TILTAKSPENGER_EKSAMENSGEBYR_ENKELTPLASS_AMO -> "TPEGEPAMO"
    StønadType.TILTAKSPENGER_SEMESTERAVGIFT_ENKELTPLASS_AMO -> "TPSAEPAMO"
    StønadType.TILTAKSPENGER_DIGITAL_JOBBKLUBB -> "TPTPDJB"
    StønadType.TILTAKSPENGER_EKSAMENSGEBYR_FORSOK_FAG_YRKESOPPLAERING -> "TPEGFFYO"
    StønadType.TILTAKSPENGER_ARBEIDSTRENINGSTILTAK -> "TPTPATT"
    StønadType.TILTAKSPENGER_RES_BASERT_FINANS_FORM_BISTAND -> "TPTPRBFINFORM"
    StønadType.TILTAKSPENGER_BARNETILLEGG_ARBEIDSFORBEREDENDE -> "TPBTAF"
    StønadType.TILTAKSPENGER_EKSAMESNSGEBYR_GR_AMO -> "TPEGGRAMO"
    StønadType.TILTAKSPENGER_BARNETILLEGG_UTV_OPPF_OPPLAERING -> "TPBTUOPPFOPPL"
    StønadType.TILTAKSPENGER_BARNETILLEGG_IPS_UNG -> "TPBTIPSUNG"
    StønadType.TILTAKSPENGER_EKSAMENSGEBYR_HOYERE_UTDANNING -> "TPEGHOYUTD"
    StønadType.TILTAKSPENGER_BARNETILSYN_ENKELPLASS_VGS_OG_HOYERE_YRKESFAG -> "TPBTEPVGSHOY"
    StønadType.TILTAKSPENGER_GRUPPE_AMO -> "TPTPGRAMO"
    StønadType.TILTAKSPENGER_BARNETILLEGG_AMO -> "TPBTAMO"
    StønadType.TILTAKSPENGER_SKOLEPENGER_ARBEIDSMARKEDSTILTAK -> "TPSPAMTILT"
    StønadType.TILTAKSPENGER_DAGLIG_REISE_AMO -> "TPDRAMO"
    StønadType.TILTAKSPENGER_BARNETILLEGG_UTVIDET_AVKLARING_OPPFOLGING -> "TPBTUAOPPFL"
    StønadType.TILTAKSPENGER_SEMESTERAVGIFT_HOYERE_UTDANNING -> "TPSAHOYUTD"
    StønadType.TILTAKSPENGER_EKSAMENSGEBYR_ENKELT_VGS_OG_HOYERE_UTDANNING -> "TPEGEPVGSHOY"
    StønadType.TILTAKSPENGER_AMO -> "TPTPAMO"
    StønadType.TILTAKSPENGER_OPPFOLGING_ANDRE_GRUPPER -> "TPTPOPPFAG"
    StønadType.TILTAKSPENGER_EKSAMENSGEBYR_ARBEIDSFORBEREDENDE -> "TPEGAFT"
    StønadType.TILTAKSPENGER_SKOLEPENGER_ENKELTPLASS_AMO -> "TPSPEPAMO"
    StønadType.TILTAKSPENGER_INDIVIDUELL_JOBBSTOTTE_UNG -> "TPTPIPSUNG"
    StønadType.TILTAKSPENGER_EKSAMENSGEBYR_ARBEIDSTRENINGSTILTAK -> "TPEGATTILT"
    StønadType.TILTAKSPENGER_UTVIDET_OPPFOLGIN_I_OPPLAERING -> "TPTPUOPPFOPPL"
    StønadType.TILTAKSPENGER_SKOLEPENGER_UTDANNING -> "TPSPUTD1"
    StønadType.TILTAKSPENGER_BARNETILLEGG_DIGITAL_JOBBKLUBB -> "TPBTDJK"
    StønadType.TILTAKSPENGER_ENKELTPLASS_AMO -> "TPTPEPAMO"
    StønadType.TILTAKSPENGER_SKOLEPENGER_ARBEIDSFORBEREDENDE -> "TPSPAFT"
    StønadType.TILTAKSPENGER_DAGLIG_REISE_AVKLARING_SKJERMET_VIRKSOMHET -> "TPDRASV"
    StønadType.TILTAKSPENGER_BARNETILLEGG_FORSOK_LENGRE_VARIGHET -> "TPBTFLV"
    StønadType.TILTAKSPENGER_SKOLEPENGER_FORSOK_HOYERE_UTDANNING -> "TPSPFHUTD"
    StønadType.TILTAKSPENGER_ARBEIDSRETTET_REHAB_ANDRE_GR__DAG -> "TPTPARREHABAGDAG"
    StønadType.TILTAKSPENGER_ARBEIDSFORBEREDENDE -> "TPTPAFT"
}
