apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-iverksett
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  ingresses:
    - https://dp-iverksett.intern.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: 1500m
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: BESLUTTER_GRUPPE
      value: "11b8475a-fb12-41aa-b1f6-8497c1b5385b"
    - name: APP_MED_SYSTEMTILGANG
      value: "dev-gcp:teamdagpenger:dp-vedtak-iverksett"
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS gir tilgang til prosessering
          - id: "97140b9a-07c5-414c-beeb-69824d04c044" # 0000-GA-Dagpenger-Prosessering-Admin gir tilgang til prosessering
          - id: "3e28466f-c53d-46da-8b44-a4abc2ad4593" # 0000-GA-Dagpenger-Saksbehandler
          - id: "11b8475a-fb12-41aa-b1f6-8497c1b5385b" # 0000-GA-Dagpenger-Beslutter
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: dp-iverksett # For testing; kan finne bruken token for app'en til å kalle seg selv
        - application: dp-vedtak-iverksett
        - application: dp-prosessering #frontend for task-rammeverket
        - application: dp-datadeling
        - application: dp-saksbehandling-frontend
        - application: dp-behandling
    outbound:
      rules:
        - application: dp-oppdrag
      external:
        - host: unleash.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        cascadingDelete: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: dp-iverksett-2
            envVarPrefix: DB
