apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltakspenger-iverksett
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  ingresses:
    - https://tiltakspenger-iverksett.intern.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 100m
  secureLogs:
    enabled: true
  leaderElection: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: BESLUTTER_GRUPPE
      value: "TODO" #Riktig beslutter-gruppe i AAD for tiltakspenger må settes her
    - name: APP_MED_SYSTEMTILGANG
      value: "dev-gcp:tpts:tiltakspenger-utbetaling"
    - name: PROSESSERING_GRUPPE
      value: "928636f4-fd0d-4149-978e-a6fb68bb19de"
  envFrom:
    - secret: tiltakspenger-iverksett-unleash-api-token
  unleash:
    environment: development
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS gir tilgang til prosessering
          - id: "97140b9a-07c5-414c-beeb-69824d04c044" # 0000-GA-Dagpenger-Prosessering-Admin gir tilgang til prosessering
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-iverksett # For testing; kan finne bruken token for app'en til å kalle seg selv
        - application: tiltakspenger-utbetaling
          namespace: tpts
        - application: dp-prosessering #frontend for task-rammeverket
    outbound:
      rules:
        - application: dp-oppdrag
      external:
        - host: dagpenger-unleash-api.nav.cloud.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        cascadingDelete: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: tiltakspenger-iverksett
            envVarPrefix: DB
